LoRa Speed Enhancements
- route incoming LoRa messages through new /sync/message route from lantern-serve
- faster display and less waiting for rx/tx of messages
- run inbox as continuous service (always scanning)
- add memory cap to broadcast service

diff --git a/src/app/service/broadcast b/src/app/service/broadcast
--- a/src/app/service/broadcast
+++ b/src/app/service/broadcast
@@ -1,216 +1,54 @@
-#!/usr/bin/env node
-var path = require("path");
-var fs = require("fs");
-var spawnSync = require('child_process').spawnSync;
-var PouchDB = require("lantern-serve").PouchDB;
+#!/bin/bash
 
-//------------------------------------------------------------------------
-var done = (function wait() { 
-    if (!done) {
-        setTimeout(wait, 1000)
-    }
-    else {
-        log.info("closing service...\n");
-        log.info("##############################################\n");
-        setTimeout(process.exit, 100);
-    }
-})();
+#
+# This script supports the following environment vars:
+#  - WEB_MEMORY: the amount of memory each
+#    process is expected to consume, in MB.
+#  - NODEJS_V8_ARGS: any additional args to
+#    pass to the v8 runtime.
 
-var logger_opts = {
-    logFilePath:'/opt/lantern/logs/broadcast.log',
-    dateFormat:'YYYY.MM.DD'
-};
+echo "=============================="
+echo "  Lantern Broadcast Service"
+echo "=============================="
 
-var log = require('simple-node-logger').createSimpleFileLogger( logger_opts );
+# Safe Limit for Raspberry Pi Zero
+WEB_MEMORY=150
 
-var identifier = getDeviceIdentifier();
+dir="/opt/lantern/bin"
+node_args="${dir}/sync-lora --color"
 
-if (!identifier) {
-    done = true;
-    return;
-}
+if [[ -n "$WEB_MEMORY" ]]; then
+  # The WEB_MEMORY environment variable is set.
+  # Set the `mem_old_space_size` flag
+  # to 4/5 of the available memory.
+  # 4/5 has been determined via trial and error
+  # to be the optimum value, to try and ensure
+  # that v8 uses all of the available memory.
+  # It's not an exact science however, and so
+  # you may need to play around with this ratio.
+  mem_node_old_space=$((($WEB_MEMORY*4)/5))
+  node_args="--max_old_space_size=$mem_node_old_space $node_args"
+fi
 
-log.info("##############################################");
-log.info("Lantern Broadcast Service (" + identifier + ")");
-log.info("##############################################\n");
-
-
-var db;
+if [[ -n "$NODEJS_V8_ARGS" ]]; then
+  # Pass any additional arguments to v8.
+  node_args="$NODEJS_V8_ARGS $node_args"
+fi
 
 
-var updated_at_limit;
+cd $dir
 
-//------------------------------------------------------------------------
-
-/**
-* unique device identifier
-*/
-function getDeviceIdentifier() {
-    try {
-        var file_path = path.join(__dirname, "..", "node_modules", "lantern-serve", "conf", "lantern.json");
-        var obj = JSON.parse(fs.readFileSync(file_path, 'utf8'));
-        if (!obj.id) {
-            throw new Error("Missing device identifier");
-        }
-        return obj.id;
-    }
-    catch(e) {
-        log.error(e);
-    }
-}
-
-/**
-* push change over distributed long-range network
-**/
-function addMessageToQueue(msg) {
-    if (!msg) return;
-    //log.info("sending message to queue: " + msg);
-    var result = spawnSync(path.resolve(__dirname + "/../bin/queue-message"), [msg]);
-    log.info(String(result.stdout));
-}
-
-/**
-* let other lanterns know about a key/value change
-**/
-function notifyDocumentUpdate(doc) {
-    var msg = buildParameters(doc);
-    if (msg.length) {
-        msg = doc._rev.split("-")[0] + "^" + doc._id + "?" + msg;
-        addMessageToQueue(msg);
-    }
-}
+echo "Starting app:"
+echo "> node $node_args"
 
 
-/**
-* let other lanterns know about a new document
-**/
-var notifyDocumentCreate = notifyDocumentUpdate;
+# Start the process using `exec`.
+# This ensures that when node exits,
+# the exit code is passed up to the
+# caller of this script.
+exec node $node_args
+
+trap : TERM INT; sleep infinity & wait
 
 
-/**
-* let other lanterns know about a removed document
-**/
-function notifyDocumentRemove(doc_id) {
-    addMessageToQueue(doc._rev.split("-")[0] + "^" + doc_id);
-}
-
-/**
-* check for updates since last broadcast revision
-*/
-function checkForChanges(since) {
-    since = (since ? Number(since) : "now");
-    log.info("find database changes since: " + since);
-
-    db.changes({
-            continuous: true,
-            since: since,
-            include_docs: true
-        })
-        .on("change", onChange)
-        .on("complete", function() {
-            log.info("[sync] complete");
-            done = true;
-        })
-        .on('error', function (err) {
-            log.error("err: ", err);
-            done = true;
-        });
-}
-
-
-/**
-* construct a query-string style list of key/value pairs
-*/
-function buildParameters(doc) {
-    var params = [];
-    for (var k in doc) {
-        // ignore private keys and reserved _ namespace items when sending
-        if (k[0] != "_" && k[0] != "$") {
-            var val = doc[k];
-
-            if (typeof val === 'number') {
-                params.push(k+"=#"+val);
-            }
-            else if (val instanceof Array) {
-                if (typeof(val[0]) == "object") {
-                    // don't try to relay objects
-                }
-                else {
-                    params.push(k+"=,"+val.join(","));
-                }
-            }
-            else if (typeof val === 'string') {
-                params.push(k+"="+val);
-            }
-            else if (typeof(val) == "object") {
-                // don't try to relay objects
-            }
-        }
-    }
-    return params.join("&");
-}
-
-function processDoc(doc) {
-
-
-    if (doc.hasOwnProperty("$rx")) {
-        log.info("skip document already received by radio: " + doc._id);
-        return;
-    }
-
-    if (doc.hasOwnProperty("$ua")) {
-        try {
-            if (updated_at_limit) {
-                var updated_at = new Date(doc.$ua).getTime();
-                var cut_off = updated_at_limit.getTime();
-                if (updated_at < cut_off) {
-                    log.info("refuse to send old document...", doc._id);
-                    return;
-                }
-            }
-            updated_at_limit = new Date(doc.$ua);
-        }
-        catch(e) {
-            log.error(e);
-            log.error("invalid updated_at field detected, ignoring...")
-            return;
-        }
-    }
-
-    if (doc._deleted) {
-        // @todo notify once we can isolate most meaningful deletes
-        log.info("cowardly refusing to send delete over network, for now...");
-        return;
-        //notifyDocumentRemove(doc._id);
-    }
-    
-    log.info("====== " + doc._id + " ======");
-    //log.info(doc);
-
-    // push change over distributed long-range network
-    if(doc._rev[0] == "1" && doc._rev[1] == "-") {
-        // assume document has been created if we're at first revision
-        notifyDocumentCreate(doc);
-    }
-    else {
-        notifyDocumentUpdate(doc);
-    }
-}
-
-/**
-* handler to process any document change in local lantern database
-**/
-function onChange(change) {
-    // log.info("change", change);
-    for (var idx in change.changes) {
-        processDoc(change.doc);
-    }
-}
-
-//------------------------------------------------------------------------
-/**
-* start listening for changes
-**/
-
-db = new PouchDB("http://localhost/db/lnt/");;
-checkForChanges();
+# credit to: https://www.fiznool.com/blog/2016/10/01/running-a-node-dot-js-app-in-a-low-memory-environment/
